name: Java CI con Maven y Doxygen Documentation

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

permissions:
  contents: read
  packages: write
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Configure MySQL
      uses: shogo82148/actions-setup-mysql@v1
      with:
        mysql-version: '8.0'
    
    - name: Initialize Database
      run: |
        mysql -h127.0.0.1 -uroot -proot < src/main/resources/dbsetup.sql
        mysql -h127.0.0.1 -uroot -proot -e "GRANT ALL PRIVILEGES ON *.* TO 'user'@'%'"
    
    - name: Compile the code
      run: mvn clean compile
    
    - name: Run Tests
      run: mvn test -DskipTests=false
      env:
        SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/restapidb
        SPRING_DATASOURCE_USERNAME: user
        SPRING_DATASOURCE_PASSWORD: password
    
    - name: Install Doxygen
      run: sudo apt-get install -y doxygen
    
    - name: Install Graphviz
      run: sudo apt-get install -y graphviz
    
    - name: Generate Doxygen Documentation
      run: doxygen src/main/resources/Doxyfile
    
    - name: Publish on Github Pages
      uses: crazy-max/ghaction-github-pages@v2.3.0
      with:
        build_dir: target/doxygen/html
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}