name: Java CI
on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml
      
      - name: Run unit tests
        run: mvn test
      
      - name: Run integration tests
        run: mvn integration-test
      
      - name: Run performance tests
        run: mvn test -Dtest=com.deustocoches.performance.*PerformanceTest
      
      - name: Generate and Archive JaCoCo Reports
        run: mvn jacoco:report
      
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4.6.2
        with:
          name: code-coverage-report
          path: target/site/jacoco/
