name: Java CI
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      
      - name: Initialize Database
        run: |
          mysql -h127.0.0.1 -uroot -proot < src/main/resources/dbsetup.sql

      - name: Unit Test
        run: mvn test

      - name: Run Integration Tests and Verify
        run: |
          mvn -Pintegration integration-test

      - name: Performance Test
        run: |
          mvn -Pperformance integration-test
                
      - name: Generate Maven Site
        run: mvn site

      - name: Copy Maven site and Doxygen output to docs folder
        run: |
          mkdir -p docs
          rm -rf docs/site
          mkdir -p docs/site
          cp -r target/site/* docs/site/ || true
          mkdir -p docs/site/reports
          cp -r rest-api/target/reports/* docs/site/reports/ || true
          rm -rf docs/doxygen
          mkdir -p docs/doxygen
          cp -r doxygen/html/* docs/doxygen/ || true
          
      #Github Actions Pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}