name: Java CI
on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: restapidb
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      
      - name: Initialize Database
        run: |
          mysql -h127.0.0.1 -uroot -proot < src/main/resources/dbsetup.sql
          mysql -h127.0.0.1 -uroot -proot -e "GRANT ALL PRIVILEGES ON *.* TO 'user'@'%'"
      
      - name: Build and Run All Tests
        run: mvn clean verify
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/restapidb
          SPRING_DATASOURCE_USERNAME: user
          SPRING_DATASOURCE_PASSWORD: password
      
      - name: Run Performance Tests
        run: mvn verify -Pperformance
        continue-on-error: true
      
      - name: Generate Coverage Report
        run: mvn jacoco:report
      
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4.6.2
        with:
          name: code-coverage-report
          path: target/site/jacoco/
