name: Java CI
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      
      - name: Initialize Database
        run: |
          mysql -h127.0.0.1 -uroot -proot < src/main/resources/dbsetup.sql

      - name: Unit Test
        run: mvn test

      - name: Run Integration Tests and Verify
        run: |
          mvn -Pintegration integration-test

      - name: Performance Test
        run: |
          mvn -Pperformance integration-test
                
      - name: Generate Maven Site
        run: mvn site

      - name: Prepare docs folder
        run: |
          mkdir -p docs
          cp README.md docs/index.md
          mkdir -p docs/doxygen
          cp -r doxygen/html/* docs/doxygen/ || true
          mkdir -p docs/site
          cp -r target/site/* docs/site/ || true
          mkdir -p docs/site/reports
          cp -r target/reports/* docs/site/reports/ || true

      - name: Install Doxygen
        run: sudo apt-get install -y doxygen
      
      - name: Install Graphviz
        run: sudo apt-get install -y graphviz
      
      - name: Generate Doxygen Documentation
        run: |
          doxygen src/main/resources/Doxyfile

      - name: Add .nojekyll file
        run: touch docs/doxygen/html/.nojekyll

      - name: Añadir .nojekyll en la raíz
        run: touch docs/.nojekyll
        
      #Para que se suban la carpeta docs a la rama gh-pages y no a la raíz
      - name: Publish on Github Pages
        uses: crazy-max/ghaction-github-pages@v2.3.0
        with:
          build_dir: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}